channels:
  - defaults
dependencies:
  - python=3.7
  - astropy=4
  - h5py=2.9
  - hdf5=1.10
  - ipython=7.8
  - joblib=0.13.2
  - matplotlib=3.1
  - notebook=6.0.1
  - numpy=1.17
  - pandas=0.25
  - pandoc=2.2.3
  - pip>=19
  - qt=5.9
  - scikit-learn=0.21
  - scipy=1.3
  - setuptools
  - sqlalchemy=1.3
  - sqlite=3
  - wheel=0.33
  - zstd=1.3
  - tqdm=4
  - pytables=3.5
  - shapely=1.6
  - numba
  - pip:
    - aict-tools==0.21.0
    - ctapipe==0.8.0
    - pyfact==0.25.2
    - eventio==1.0.0
    - zstandard
    - https://github.com/cta-observatory/ctapipe-extra/archive/v0.3.0.tar.gz
    - https://github.com/fact-project/fact_plots/archive/v0.12.2.tar.gz
    - https://github.com/fact-project/irf/archive/v0.5.0.tar.gz
    - https://github.com/fact-project/fact_funfolding/archive/v0.3.4.tar.gz
